### ISSUE TITLE
Display scoreboard with initials and scores

### ISSUE THREAD

**Issue by kwilks3** [kwilks3/Code-Quiz#18]
make scoreboard

**Comment by antoniojgage** [comment]
@kwilks3 I spotted a few bugs here but it does look like the root cause is you're not saving an object or array of scores into local storage. We need to JSON.strinigify the high scores then save it into local storage then parse it on the way out.
<img width="1382" alt="Screen Shot 2020-05-11 at 2 05 04 PM" src="https://user-images.githubusercontent.com/7440005/81601606-c05b3d00-9390-11ea-99c9-8e14d07a8bf8.png">
